model:
  decoder:      # 解码器配置
    backbone:
      type: SECOND      # 主干网络类型，这里是SECOND
      in_channels: 256
      out_channels: [128, 256]
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      norm_cfg:
        type: BN
        eps: 1.0e-3
        momentum: 0.01
      conv_cfg:     # 卷积配置，使用Conv2d，不使用偏置（bias: false）
        type: Conv2d
        bias: false
    neck:     # 特征金字塔网络类型，这里是SECONDFPN
      type: SECONDFPN
      in_channels: [128, 256]
      out_channels: [256, 256]
      upsample_strides: [1, 2]
      norm_cfg:
        type: BN
        eps: 1.0e-3
        momentum: 0.01
      upsample_cfg:     # 上采样配置，使用反卷积（deconv），不使用偏置（bias: false）
        type: deconv
        bias: false
      use_conv_for_no_stride: true
  heads:
    object:
      in_channels: 512

optimizer:
  type: AdamW
  lr: 1.0e-4
  weight_decay: 0.01

optimizer_config:
  grad_clip:
    max_norm: 35
    norm_type: 2

lr_config:      # 学习率调度策略，这里是cyclic，表示使用循环学习率
  policy: cyclic

momentum_config:      # 动量调度策略，这里是cyclic，表示使用循环动量
  policy: cyclic
